name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://cqa.samfrew.com/7a58c4a2d9f88225/a65bf336f3d747215f8138e8608aa099cace023ec7481a8cf7cfaf9bc36b8c1dc07bdb1005fec0df8d2f14bacd7dedff6496c08a46aa523627afea71f555c81148253179dd0f722b9449db46196a6f6fbd4ffabb1a3c94cf3167cb6de80e75ab0d1113ff3e53c324ee78e1df812a26fd961588eb008fcf87a70d0fe561aa13f0a19900e416a5fa8393f65982e43d31f864928d379e5bbe547ebce65de5a2f7c8/TGY-G8850ZHU5CTL1-20210111135824.zip
  ROM_NAME: one ui
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit final/GSI.zip

         
            
